site_name: Xiaotian Tian's Secret Garden
site_url: https://er1kka-tian.github.io/
theme:
  name: material
  font:
    text: Libertinus Sans
    code: Red Hat Mono
  logo: assets/profile_pic.png
  favicon: assets/profile_pic.png
  features:
    - navigation.footer
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.path
    - navigation.prune
    - toc.follow
    - toc.integrate
    - content.code.annotate
    - content.action.edit
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: pink
      accent: indigo

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: pink
      accent: indigo 

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: pink
      accent: indigo


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: material/linkedin
      link: https://www.linkedin.com/in/xiaotian-tian/
    - icon: material/github
      link: https://github.com/Er1kKa-Tian
    - icon: material/email
      link: mailto:er1kka.tian@outlook.com

extra_css:
  # Your custom map styles
  - stylesheets/extra.css
  # OpenLayers CSS
  - https://cdn.jsdelivr.net/npm/ol@latest/ol.css


extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/ol@latest/dist/ol.js
  - javascripts/maps/registry.js   # exposes window.buildMap
  - javascripts/maps/index.js      # calls window.buildMap             

nav:
  - Home: index.md
  - My Background: about.md
  - Academic:
      - Overview: academic/academic_index.md
  - Projects:
      - Overview: projects/project_index.md
      - ATO Priority Project Pipeline Database: projects/ato_pipeline.md
      - ATO Aviation Country Profile: projects/ato_aviation.md
  - How I Learned Everything?: 
      - Main page: learning/learning_index.md
      - Methodology:  learning/methodology.md
      - Oxford MPhil Economics:
          - Overview: learning/ox_mphil_econ/ox_mphil_econ_index.md
      - Progress Tracker: learning/tracker.md
  - Resources:
      - UCL BSc Econ Notes: resources/ucl_notes.md
      - Oxford MPhil Econ Notes: resources/ox_notes.md
  - Travel:
      - Overview: travel/travel_index.md
      - UK:
        - Brockenhurst: travel/uk/brockenhurst.md
      - Europe:
        - Bosnia and Herzegovina: travel/europe/bosnia_and_herzegovina.md
  - Personal:
    - Overview: personal/personal_index.md
    - with Yangyang: personal/yangyang/yangyang_index.md
    - Friends: personal/friends.md
  - Misc:
    - Aviation Profile Sample: misc/ato_aviation_profile_test.md

copyright: Copyright &copy; 2025 Xiaotian Tian