---
title: "mphil_decile_visualise"
format: html
editor: visual
---

```{r}
library(tidyverse)
```

```{r}
decile_2025 <- tibble(
  decile = c(1, 2, 3, 4, 5, 6, 7, 8, 9),
  micro = c(45, 50, 53, 58, 62, 66, 69, 73, 80),
  macro = c(50, 56, 59, 61, 64, 66, 67, 69, 72.6),
  metrics = c(50.6, 55.2, 57.8, 61, 64, 65.6, 66.2, 68, 70.4),
  agg = c(50, 53.3, 56.8, 61.3, 63.0, 65.5, 67.7, 70.7, 74)
)

decile_2024 <- tibble(
  decile = c(1, 2, 3, 4, 5, 6, 7, 8, 9),
  micro = c(60, 60, 60, 63, 67, 71, 76, 78, 82),
  macro = c(51, 57, 59, 61, 62, 64, 66, 70, 73),
  metrics = c(54, 57, 60, 61, 63, 65, 66, 68, 72.5),
  agg = c(56.3, 59, 60, 61.3, 62.4, 65, 69.2, 71.3, 74.7)
)

decile_2023 <- tibble(
  decile = 1:9,
  micro = c(45, 51.2, 53.0, 59.4, 63.0, 66.6, 70.2, 73.8, 79.8),
  macro = c(52.0, 54.4, 60.6, 63.8, 67.0, 68.2, 70.0, 72.0, 73.8),
  metrics = c(56.9, 59.0, 61.0, 62.0, 64.0, 66.0, 68.0, 70.0, 71.2),
  agg = c(50.7, 55.7, 59.0, 61.3, 63.5, 68.0, 70.5, 71.7, 74.5)
)

decile_2022 <- tibble(
  decile = 1:9,
  micro = c(49.2, 53.2, 55.6, 59.4, 61.5, 64.6, 65.0, 70.6, 73.0),
  macro = c(54.7, 57.8, 60.0, 61.0, 63.0, 63.8, 65.3, 68.0, 70.0),
  metrics = c(56.8, 58.6, 60.4, 62.2, 64.0, 66.0, 67.0, 68.0, 71.2),
  agg = c(53.8, 55.7, 60.3, 61.7, 63.7, 65.3, 66.7, 69.0, 71.2)
)

```

```{r}
decile_2025 |>
  ggplot(
    mapping = aes(x = micro, y = decile)
  ) +
  geom_point(color = "blue") +
  geom_vline(xintercept = c(50, 65, 70), 
             linetype = "dashed", 
             color = "red") +
  labs(title = "Core Modules Distributions") +
  annotate("text", y = 10.3, x = c(50, 65, 70),
           label = c("Pass", "Meris", "Distinction"),
           hjust = -0.3, vjust = 0,
           color = "red", size = 3.5) +
  xlab("Score") +
  ylab("Decile") +
  scale_y_continuous(breaks = 1:10) +
  theme_bw()
```

```{r}
plot_deciles <- function(decile_tbl, title, caption){

# Reshape data to long format
decile_long <- decile_tbl %>%
  pivot_longer(cols = c(micro, macro, metrics, agg),
               names_to = "category",
               values_to = "score")

# Plot
ggplot(decile_long, aes(x = score, y = decile, color = category, linetype = category)) +
  geom_point(size = 2, shape = 3) +
  geom_line(aes(group = category), linewidth = 0.8, alpha = 0.4) +
  geom_vline(xintercept = c(50, 65, 70), 
             linetype = "dashed", 
             color = "red") +
  annotate("text", y = 9.8, x = c(50, 65, 70),
           label = c("Pass", "Merit", "Distinction"),
           hjust = -0.2, vjust = -0.3,
           color = "red", size = 3.52) +
  scale_linetype_manual(
    values = c("micro" = "dashed", "macro" = "dashed",
               "metrics" = "dashed", "agg" = "solid")
  ) +
  scale_color_manual(
    values = c("micro" = "blue", "macro" = "brown", 
              "metrics" = "green", "agg" = "red"), 
    labels = c(
      "micro" = "Micro",
      "macro" = "Macro",
      "metrics" = "Metrics",
      "agg" = "Aggregate Score"
    )) +
  scale_y_continuous(breaks = 1:10) +
  scale_x_continuous(
    limits = c(45, 85),
    breaks = seq(45, 85, by = 5)   # ticks every 5
  ) +
  labs(
    title = title,
    caption = caption,
    x = "Score",
    y = "Decile",
    color = "Module"
  ) +
  guides(linetype = "none") +
  theme_bw()

}
```

```{r}
plot_2025 <- plot_deciles(decile_2025, "Core Modules Distributions: 1st - 9th Deciles (2025)", "")
plot_2025
```

```{r}
ggsave(
  filename = "decile_plot_2025.png",  # file name
  plot = plot_2025,                 # or specify your ggplot object
  width = 8, height = 5,              # in inches
  dpi = 300                           # high-resolution
)
```

```{r}
plot_2024 <- plot_deciles(decile_2024, "Core Modules Distributions: 1st - 9th Deciles (2024)", "Micro was re-examed and truncated at 60 due to a mistake in distributing exam papers.")
plot_2024
```

```{r}
ggsave(
  filename = "decile_plot_2024.png",  # file name
  plot = plot_2024,                 # or specify your ggplot object
  width = 8, height = 5,              # in inches
  dpi = 300                           # high-resolution
)
```

```{r}
plot_2023 <- plot_deciles(decile_2023, "Core Modules Distributions: 1st - 9th Deciles (2023)", "")
plot_2023
```

```{r}
ggsave(
  filename = "decile_plot_2023.png",  # file name
  plot = plot_2024,                 # or specify your ggplot object
  width = 8, height = 5,              # in inches
  dpi = 300                           # high-resolution
)
```

```{r}
plot_2022 <- plot_deciles(decile_2022, "Core Modules Distributions: 1st - 9th Deciles (2022)", "")
plot_2022
```

```{r}
ggsave(
  filename = "decile_plot_2022.png",  # file name
  plot = plot_2024,                 # or specify your ggplot object
  width = 8, height = 5,              # in inches
  dpi = 300                           # high-resolution
)
```
